## 每个区域的货运数量 (默认: 25)
amount: 25

## 自动更新 (默认: false)
auto-update: false

## 线程池大小 (默认: 4)
## 如果你更改此设置,请确保你清楚你在做什么!
thread-pool-size: 4

## 如果服务器拥有领地类型的插件，则玩家无法在领地外放置货运节点等
## 这将阻止从领地外延伸货运系统并偷取物品
block-wilderness-cargo: false

## 启用权限 (默认为false,关闭)
## 权限节点: headlimiter.permission.<name>
## 例子: headlimiter.permission.noob
##
## 当开启权限时，你可以设置权限对应的头颅数量上限
## 权限节点的数量应从大到小排序（参考默认顺序）
permissions: false
permission:
  ## sefi: 25
  ## walshy: 20
  ## alessio: 15
  ## jeff: 10
  noob: 5